spring:
  application:
    name: ms-transaction-service
  profile:
    active: development
  config:
    import: optional:configserver:http://ms-config-server:7070
    #import: optional:configserver:http://localhost:7070